# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://blog.zuwei.top
date_format: "ordinal"
title: 有且可为
subtitle: "祖为的个人博客"
description: "祖为的个人博客"
keywords: 祖为, zuwei, 有且可为, 博客, blog
timezone: Asia/Shanghai
encoding: "utf-8"
# 页面左下角显示的年份
since: 2023
# 源码仓库，请替换成自己的
repository: zuwei522/zuwei522.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: 
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2023-08-23
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 3
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: true
        file_name: wulang.png
        image_alt: 五郎
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
    # 图片灯箱效果功能
    fancybox:
        enabled: true
    # 页脚 IPv6 标识
    ipv6:
        enabled: true
        domain_name: blog.zuwei.top
    # 页脚备案信息显示
    icp:
        enabled: true
        text: 萌ICP备20230841号
        link: https://icp.gov.moe/?keyword=20230841
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: molokai

# ---------------- #
#      Author      #
# ---------------- #
author: Jiang Zuwei
organization: GUET
organization_url: https://www.guet.edu.cn/gdbh/
github_username: zuwei522
location: Beihai, China
email: jiang@zuwei.top

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档
    mobile-hidden: true

  -
    href: /open-source/
    label: 开源
    mobile-hidden: true

  -
    href: /fragments/
    label: 片段

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接
    mobile-hidden: true

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# disqus 配置参考：https://disqus.com
disqus:
    username: 
# gitment 配置参考：https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zuwei522
    repo: blog-comments
    oauth:
        client_id: 
        client_secret: 
# gitalk 配置参考：https://github.com/gitalk/gitalk#install
gitalk:
    owner: zuwei522
    repo: blog-comments
    clientID: 
    clientSecret: 
# utterances 配置参考：https://utteranc.es/
utterances:
    repo: zuwei522/blog-comments
# beaudar 配置参考：https://beaudar.lipk.org/
beaudar:
    repo: zuwei522/blog-comments
# giscus 配置参考：https://giscus.app/zh-CN
giscus:
    repo: zuwei522/zuwei522.github.io
    repo-id: R_kgDOKKcnfQ
    category: Announcements
    category-id: DIC_kwDOKKcnfc4CYz7i
    mapping: pathname

# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: G-RY79YHGVGE
    adsense:
        enabled: false
        data-ad-client: ca-pub-7565690999339141
        footer: false
        sidebar: true
        sidebar-detail: true
        content_header: false
        content_footer: false
